version: "3.9"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8082:80"

  whoami:
    image: containous/whoami
    ports:
      - "8083:80"
